# Generated by Django 2.1 on 2018-08-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_manager',
            new_name='is_staff',
        ),
    ]
